### ISSUE TITLE
[vioarr] amd64 opengl not rendering correctly

### ISSUE THREAD

**Issue by Manish-Kala-Jaat** [Meulengracht/MollenOS#213] opened 2019-04-29 06:08 UTC
I just compiled the latest commit of mollen os repository and generated the vmdk file and tried to run it in the virtual box but it shows the startup debug console and stuck it out there.
the last line which it shows on the debug console is =
[LIBC] Spawning message handler.

**Screenshots**
![एनोटेशन 2019-04-29 100020](https://user-images.githubusercontent.com/49841018/56878736-31280380-6a73-11e9-9c26-93b0230bc723.jpg)

**Comment by Meulengracht** [comment] 2019-04-29 08:01
Are you running with multiple cores? Just for my own information when I reproduce this later

**Comment by Manish-Kala-Jaat** [comment] 2019-04-29 08:05
check it up in this pic=

![एनोटेशन 2019-04-29 133428](https://user-images.githubusercontent.com/49841018/56883223-a7346680-6a83-11e9-87d3-5f0b3f7ea090.jpg)

**Comment by Manish-Kala-Jaat** [comment] 2019-04-29 08:13
well for your help ,I am sending more screenshots=

![एनोटेशन 2019-04-29 133952](https://user-images.githubusercontent.com/49841018/56883552-acde7c00-6a84-11e9-9395-32645b2320b6.jpg)

![एनोटेशन 2019-04-29 133925](https://user-images.githubusercontent.com/49841018/56883578-b8ca3e00-6a84-11e9-93e4-bce330d67fcd.jpg)

![एनोटेशन 2019-04-29 134018](https://user-images.githubusercontent.com/49841018/56883591-c384d300-6a84-11e9-9fbd-78c6f33c3676.jpg)

**Comment by Meulengracht** [comment] 2019-04-29 08:34
Perfect thanks - I’ll look into it. It looks like the renderer is stuck. It most likely a side effect from the recent multi core improvements

**Comment by Manish-Kala-Jaat** [comment] 2019-04-29 08:39
sure

**Comment by Meulengracht** [comment] 2019-04-29 18:57
This is because of #198 . It needs to be fixed before the 64 bit version of llvm's code generation for shaders is working. I would recommend you use the 32 bit version of everything untill #198 is fixed.

**Comment by Meulengracht** [comment] 2019-04-29 18:59
You can see the error messages if you go into vali-userspace/vioarr/vioarr.cpp and comment out line 65

**Comment by Manish-Kala-Jaat** [comment] 2019-04-30 02:25
Sure man

**Comment by Meulengracht** [comment] 2019-04-30 19:10
This is due to something else. Discovered that issue #198 was not an issue after all :-) I'll keep looking into this!

**Comment by Meulengracht** [comment] 2019-05-01 06:20
I was using the wrong calling convention for the assembly function responsible for copying the back buffer to the screen. This resulted in some undefined behavior which most likely is the cause. If you get the latest source for vali-userspace this should be fixed now

**Comment by Manish-Kala-Jaat** [comment] 2019-05-01 15:26
I tried it but now it stuck in the ahead part , it shows the green screen .
screenshot: ->
![Screenshot (5418)](https://user-images.githubusercontent.com/49841018/57024953-7c990800-6c53-11e9-9795-05276d59d886.png)

**Comment by Meulengracht** [comment] 2019-05-01 15:46
Yes I discovered - I have yet to determine what the issue is on this issue, I have to investigate the difference between the i368 and amd64 build for Mesa. I do suspect a few things tho.

**Comment by Meulengracht** [comment] 2019-05-02 06:57
It'll take a few days for me to fix this most likely, or atleast understand what the issue is. (I don't have time before the weekend), untill then use the 32 bit distribution if you just want to try it.

**Comment by Meulengracht** [comment] 2019-05-05 13:00
The render issue has been resolved. It had to do with the wrong 64 bit calling convention used by mesa in its code generation (mollenos is using the same as windows, which needs to be specified). There is an issue with input (key events) in 64 bit mode. I'm looking into that. I'll open a new issue for that

**Closed by Meulengracht** 2019-05-05 13:00 UTC
Labels: bug, critical
